name = input('I could care less but, what is your name? ')
print(name.upper() + '?!?!?!?' + 'I HATE THAT NAME IS REALLY SUCKS!')
color = input('What is your favorite color? ')
print(color.upper() + '!!!!!' + ' OUT OF ALL THE COLORS YOU COULD OF PICK YOU CHOOSE ' + color.upper() + '?!??!?!?')
school = input('What is your favortie subject? ')
print(school.upper() + '!?!?!? ' + " YOU'RE SUCH A NERD, EWWWW!!!!!")
show = input('What is your favorite T.V show? ')
print(show.upper() + '?!?!?!?' + " I bet it's not as good as SyFy's The Magicans!!!!")